services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod.local
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "${APP_PORT:-3000}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.corridas.rule=Host(`circuitodascorridas.com.br`)"
      - "traefik.http.routers.corridas.entrypoints=websecure"
      - "traefik.http.routers.corridas.tls=true"
      - "traefik.http.routers.corridas.tls.certresolver=mytlschallenge"
      - "traefik.http.services.corridas.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.corridas-http.rule=Host(`circuitodascorridas.com.br`)"
      - "traefik.http.routers.corridas-http.entrypoints=web"
      - "traefik.http.routers.corridas-http.middlewares=corridas-https-redirect"
      - "traefik.http.middlewares.corridas-https-redirect.redirectscheme.scheme=https"
    networks:
      - proxy
      - corridas_internal

networks:
  proxy:
    external: true
    name: proxy
  corridas_internal:
    external: true
    name: corridas_internal
